export const ROUTES = {
  home: '/',
  shop: '/shop',
  products: '/products',
  product: (slug: string) => `/products/${slug}`,
  cart: '/cart',
  checkout: '/checkout',
  payment: {
    success: '/payment/success',
    failed: '/payment/failed',
    pending: '/payment/pending',
    result: '/thanh-toan/ket-qua',
  },
  account: {
    profile: '/tai-khoan/ho-so',
    password: '/tai-khoan/doi-mat-khau',
    addresses: '/tai-khoan/dia-chi',
    orders: '/tai-khoan/don-hang',
    order: (id: string) => `/tai-khoan/don-hang/${id}`,
  },
  auth: {
    login: '/auth/login',
    register: '/auth/register',
  },
  company: {
    ourStory: '/ve-chung-toi/cau-chuyen',
    vision: '/ve-chung-toi/tam-nhin',
    mission: '/ve-chung-toi/su-menh',
    coreValues: '/ve-chung-toi/gia-tri-cot-loi',
  },
  admin: {
    root: '/admin',
    dashboard: '/admin/dashboard',
    products: '/admin/products',
    categories: '/admin/categories',
    brands: '/admin/brands',
    inventory: '/admin/inventory',
    orders: '/admin/orders',
    payments: '/admin/payments',
    customers: '/admin/customers',
    vouchers: '/admin/vouchers',
    chat: '/admin/chat',
    settings: '/admin/settings',
    users: '/admin/users',
    reviews: '/admin/reviews',
    variants: '/admin/variants',
  },
} as const;
